DROP DATABASE IF EXISTS formation;

CREATE DATABASE IF NOT EXISTS formation;
USE formation;

CREATE TABLE IF NOT EXISTS commande(
ID INTEGER NOT NULL AUTO_INCREMENT, 
commandeName VARCHAR(25) NOT NULL, 
commandeDate DATE, 
commandeTotal INTEGER,
PRIMARY KEY(ID)
) ENGINE=InnoDB ;

CREATE TABLE IF NOT EXISTS plat(
ID INTEGER NOT NULL AUTO_INCREMENT, 
platName VARCHAR(25) NOT NULL, 
platTarif INTEGER,
PRIMARY KEY(ID)
) ENGINE=InnoDB ;

CREATE TABLE IF NOT EXISTS ingredient(
ID INTEGER NOT NULL AUTO_INCREMENT, 
ingredientName VARCHAR(25),
PRIMARY KEY(ID)
) ENGINE=InnoDB ;

CREATE TABLE IF NOT EXISTS commande_plats(
ID INTEGER NOT NULL AUTO_INCREMENT, 
commandeID INTEGER,
platID INTEGER,
PRIMARY KEY(ID),
CONSTRAINT FK_cmdPlat_commandeID FOREIGN KEY(commandeID) REFERENCES formation.commande(id) ON DELETE CASCADE,
CONSTRAINT FK_cmdPlat_platID FOREIGN KEY(platID) REFERENCES formation.plat(id) ON DELETE CASCADE
) ENGINE=InnoDB ;

CREATE TABLE IF NOT EXISTS plat_ingredients(
platID INTEGER NOT NULL, 
ingredientID INTEGER NOT NULL, 
quantite INTEGER,
PRIMARY KEY (platID, ingredientID),
CONSTRAINT FK_platIngr_platID FOREIGN KEY(platID) REFERENCES formation.plat(ID) ON DELETE CASCADE,
CONSTRAINT FK_platIngr_ingredientID FOREIGN KEY(ingredientID) REFERENCES formation.ingredient(ID) ON DELETE CASCADE
) ENGINE=InnoDB ;

CREATE TABLE IF NOT EXISTS depot(
ingredientID INTEGER NOT NULL AUTO_INCREMENT, 
depotDate DATE,
quantite INTEGER,
PRIMARY KEY (ingredientID, depotDate),
CONSTRAINT FK_ingredientID FOREIGN KEY(ingredientID) REFERENCES formation.ingredient(ID) ON DELETE CASCADE
) ENGINE=InnoDB ;